export type LocalizedText = { zh: string; en: string; ja: string };

export type SeedCategory = "TRANSPORT" | "SIGHT" | "FOOD" | "LODGING" | "SHOPPING" | "FREE" | "OTHER";

export type SeedItineraryItem = {
  startTime: string | null;
  endTime: string | null;
  category: SeedCategory;
  title: LocalizedText;
  locationName: LocalizedText | null;
  note: LocalizedText | null;
  cost: number | null;
  url: string | null;
};

export type SeedDay = {
  date: string;
  title: LocalizedText;
  items: SeedItineraryItem[];
};

export const TRIP_META = {
  name: {
    zh: "马来西亚：马六甲・怡保・槟城・吉隆坡",
    en: "Malaysia — Melaka, Ipoh, Penang & KL",
    ja: "マレーシア：マラッカ・イポー・ペナン・KL",
  } satisfies LocalizedText,
  destination: { zh: "马来西亚", en: "Malaysia", ja: "マレーシア" } satisfies LocalizedText,
  startDate: "2026-10-24",
  endDate: "2026-11-01",
  currency: "MYR",
};

export const MALAYSIA_TRIP_DAYS: SeedDay[] = [
  {
    date: "2026-10-24",
    title: { zh: "马六甲", en: "Melaka", ja: "マラッカ" },
    items: [
      {
        startTime: "08:30",
        endTime: null,
        category: "TRANSPORT",
        title: { zh: "直达巴士前往马六甲", en: "Direct coach to Melaka", ja: "マラッカ行き直行バス" },
        locationName: { zh: "吉隆坡国际机场 (KLIA)", en: "KLIA", ja: "KLIA" },
        note: {
          zh: "约早上 06:00 抵达 KLIA，办理入境、领取行李并吃早餐，约 08:30–09:00 乘直达巴士前往马六甲。",
          en: "Arrive KLIA around 06:00, complete immigration, collect luggage and have breakfast, then take a direct coach around 08:30–09:00 to Melaka.",
          ja: "午前6時ごろKLIAに到着、入国審査・荷物受け取り・朝食を済ませ、午前8時30分〜9時ごろの直行バスでマラッカへ。",
        },
        cost: 30,
        url: null,
      },
      {
        startTime: "10:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "荷兰广场・圣保罗山史迹", en: "Dutch Square & St. Paul's Hill", ja: "オランダ広場・セントポールの丘" },
        locationName: { zh: "鸡场街周边", en: "Jonker Street area", ja: "ジョンカー・ストリート周辺" },
        note: {
          zh: "把行李寄放在鸡场街附近，然后参观荷兰红屋广场、基督堂、圣保罗山、A Famosa 和马六甲河畔。",
          en: "Leave luggage near Jonker Street, then visit Dutch Square, Christ Church, St. Paul's Hill, A Famosa and the riverside.",
          ja: "ジョンカー・ストリート周辺に荷物を預け、オランダ広場、キリスト教会、セントポールの丘、A Famosa、川沿いを観光。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "19:00",
        endTime: null,
        category: "SHOPPING",
        title: { zh: "鸡场街夜市", en: "Jonker Street Night Market", ja: "ジョンカー・ストリート・ナイトマーケット" },
        locationName: { zh: "鸡场街", en: "Jonker Street", ja: "ジョンカー・ストリート" },
        note: {
          zh: "晚上逛鸡场街夜市；马六甲河游船可视体力选择。",
          en: "Evening at Jonker Street Night Market; Melaka River Cruise is optional.",
          ja: "夜はジョンカー・ストリートのナイトマーケットへ。川クルーズは体力次第です。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: null,
        endTime: null,
        category: "LODGING",
        title: { zh: "入住马六甲民宿（1晚）", en: "Check in Melaka accommodation (1 night)", ja: "マラッカの宿にチェックイン（1泊）" },
        locationName: { zh: "鸡场街周边", en: "Jonker Street area", ja: "ジョンカー・ストリート周辺" },
        note: { zh: "住宿：马六甲。", en: "Sleep: Melaka.", ja: "宿泊：マラッカ。" },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-10-25",
    title: { zh: "马六甲 → 怡保", en: "Melaka → Ipoh", ja: "マラッカ → イポー" },
    items: [
      {
        startTime: "08:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "青云亭・历史街区散步", en: "Cheng Hoon Teng Temple & heritage walk", ja: "青雲亭寺院・歴史地区散策" },
        locationName: { zh: "鸡场街・青云亭", en: "Jonker Street / Cheng Hoon Teng Temple", ja: "ジョンカー・ストリート/青雲亭" },
        note: {
          zh: "早餐后逛鸡场街、青云亭和附近历史街区。",
          en: "Breakfast and a short walk around Jonker Street, Cheng Hoon Teng Temple and the heritage streets.",
          ja: "朝食後、ジョンカー・ストリート、青雲亭寺院、歴史地区を散策。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "10:30",
        endTime: null,
        category: "TRANSPORT",
        title: { zh: "直达巴士前往怡保", en: "Direct coach to Ipoh", ja: "イポー行き直行バス" },
        locationName: { zh: "马六甲中央车站", en: "Melaka Sentral", ja: "マラッカ・セントラル" },
        note: {
          zh: "上午从马六甲中央车站乘直达巴士前往怡保 Amanjaya，预计约 5–6 小时。",
          en: "Take a morning direct coach from Melaka Sentral to Ipoh/Amanjaya, allowing roughly 5–6 hours.",
          ja: "午前中にマラッカ・セントラルからイポー/Amanjaya行きの直行バスに乗り、約5〜6時間を見込みます。",
        },
        cost: 55,
        url: null,
      },
      {
        startTime: null,
        endTime: null,
        category: "LODGING",
        title: { zh: "入住怡保民宿（1晚）", en: "Check in Ipoh accommodation (1 night)", ja: "イポーの宿にチェックイン（1泊）" },
        locationName: { zh: "怡保旧城区", en: "Ipoh Old Town", ja: "イポー旧市街" },
        note: { zh: "住宿：怡保。", en: "Sleep: Ipoh.", ja: "宿泊：イポー。" },
        cost: null,
        url: null,
      },
      {
        startTime: "18:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "怡保旧城区夜游", en: "Ipoh Old Town evening walk", ja: "イポー旧市街の夜散策" },
        locationName: { zh: "怡保旧城区", en: "Ipoh Old Town", ja: "イポー旧市街" },
        note: {
          zh: "晚上游览怡保旧城区、火车站、桦树纪念钟楼、二奶巷和壁画。",
          en: "Evening in Ipoh Old Town: railway station, Birch Memorial Clock Tower, Concubine Lane and murals.",
          ja: "夜はイポー旧市街、駅、バーチ記念時計塔、コンキュバイン・レーン、壁画を巡ります。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "19:30",
        endTime: null,
        category: "FOOD",
        title: { zh: "品尝怡保白咖啡", en: "Ipoh white coffee", ja: "イポー・ホワイトコーヒー" },
        locationName: { zh: "怡保旧城区", en: "Ipoh Old Town", ja: "イポー旧市街" },
        note: {
          zh: "并品尝怡保白咖啡。",
          en: "Round off the evening with Ipoh white coffee.",
          ja: "ホワイトコーヒーを楽しみます。",
        },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-10-26",
    title: { zh: "怡保 → 槟城", en: "Ipoh → Penang", ja: "イポー → ペナン" },
    items: [
      {
        startTime: "09:00",
        endTime: null,
        category: "FOOD",
        title: { zh: "悠闲早晨・早午餐", en: "Relaxed morning & early lunch", ja: "のんびり午前・早めの昼食" },
        locationName: { zh: "怡保旧城区", en: "Ipoh Old Town", ja: "イポー旧市街" },
        note: {
          zh: "早上悠闲游览怡保旧城区并早点吃午餐。",
          en: "Relaxed morning in Ipoh Old Town and early lunch.",
          ja: "午前中はイポー旧市街をゆっくり散策し、早めの昼食を取ります。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "13:00",
        endTime: null,
        category: "TRANSPORT",
        title: { zh: "ETS火车＋渡轮前往乔治市", en: "ETS train + ferry to George Town", ja: "ETS＋フェリーでジョージタウンへ" },
        locationName: { zh: "怡保火车站", en: "Ipoh railway station", ja: "イポー駅" },
        note: {
          zh: "乘 ETS/KTM 前往北海 Butterworth，再搭渡轮到乔治市。",
          en: "Take ETS/KTM from Ipoh to Butterworth, then ferry to George Town.",
          ja: "ETS/KTMでバターワースへ行き、フェリーでジョージタウンへ渡ります。",
        },
        cost: 35,
        url: null,
      },
      {
        startTime: null,
        endTime: null,
        category: "LODGING",
        title: { zh: "入住乔治市民宿（2晚）", en: "Check in George Town accommodation (2 nights)", ja: "ジョージタウンの宿にチェックイン（2泊）" },
        locationName: { zh: "乔治市・Macalister", en: "George Town / Macalister", ja: "ジョージタウン/マカリスター" },
        note: { zh: "住宿：槟城。", en: "Sleep: Penang.", ja: "宿泊：ペナン。" },
        cost: null,
        url: null,
      },
      {
        startTime: "18:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "姓周桥・亚美尼亚街壁画区", en: "Chew Jetty & Armenian Street art", ja: "チュー・ジェティ・アルメニアン・ストリート" },
        locationName: { zh: "乔治市", en: "George Town", ja: "ジョージタウン" },
        note: {
          zh: "晚上游览姓周桥、亚美尼亚街、壁画区。",
          en: "Evening around Chew Jetty, Armenian Street and street art.",
          ja: "夜はチュー・ジェティ、アルメニアン・ストリート、ストリートアートへ。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "19:30",
        endTime: null,
        category: "FOOD",
        title: { zh: "牛干冬街或汕头街晚餐", en: "Dinner at Chulia Street or Kimberley Street", ja: "チュリア/キンバリー・ストリートで夕食" },
        locationName: { zh: "牛干冬街・汕头街", en: "Chulia Street / Kimberley Street", ja: "チュリア・ストリート/キンバリー・ストリート" },
        note: {
          zh: "在牛干冬街或汕头街附近吃晚餐。",
          en: "Dinner around Chulia Street or Kimberley Street.",
          ja: "チュリア・ストリートまたはキンバリー・ストリートで夕食。",
        },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-10-27",
    title: { zh: "槟城一日游", en: "Penang full day", ja: "ペナン一日観光" },
    items: [
      {
        startTime: "07:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "升旗山", en: "Penang Hill", ja: "ペナン・ヒル" },
        locationName: { zh: "升旗山", en: "Penang Hill", ja: "ペナン・ヒル" },
        note: {
          zh: "约 07:00–07:30 前往升旗山。",
          en: "Leave around 07:00–07:30 for Penang Hill.",
          ja: "午前7時〜7時30分ごろにペナン・ヒルへ。",
        },
        cost: 40,
        url: null,
      },
      {
        startTime: "10:30",
        endTime: null,
        category: "SIGHT",
        title: { zh: "极乐寺・亚依淡午餐", en: "Kek Lok Si Temple & Air Itam lunch", ja: "極楽寺・エア・イタムで昼食" },
        locationName: { zh: "亚依淡", en: "Air Itam", ja: "エア・イタム" },
        note: {
          zh: "参观极乐寺并在亚依淡吃午餐。",
          en: "Followed by Kek Lok Si Temple and lunch in Air Itam.",
          ja: "その後、極楽寺とエア・イタムで昼食。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "14:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "邱公司・小印度・海滨公园", en: "Khoo Kongsi, Little India & Esplanade", ja: "クー・コンシー・リトル・インディア・エスプラネード" },
        locationName: { zh: "乔治市", en: "George Town", ja: "ジョージタウン" },
        note: {
          zh: "下午和晚上游览邱公司、小印度、甲必丹吉宁清真寺一带、海滨公园、蓝屋附近和乔治市历史街区。",
          en: "Afternoon and evening: Khoo Kongsi, Little India, Kapitan Keling Mosque area, Esplanade, Blue Mansion area and George Town heritage streets.",
          ja: "午後から夜はクー・コンシー、リトル・インディア、カピタン・クリン・モスク周辺、エスプラネード、ブルー・マンション周辺、ジョージタウン歴史地区を巡ります。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "19:00",
        endTime: null,
        category: "FOOD",
        title: { zh: "槟城美食巡礼", en: "Penang food circuit", ja: "ペナン・グルメ巡り" },
        locationName: { zh: "乔治市", en: "George Town", ja: "ジョージタウン" },
        note: {
          zh: "重点美食：亚参叻沙、炒粿条、福建面、印度香料饭和煎蕊。",
          en: "Food targets: assam laksa, char kway teow, Hokkien mee, nasi kandar and cendol.",
          ja: "アッサムラクサ、チャークイティオ、福建麺、ナシカンダール、チェンドルもおすすめです。",
        },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-10-28",
    title: { zh: "槟城 → 吉隆坡", en: "Penang → Kuala Lumpur", ja: "ペナン → クアラルンプール" },
    items: [
      {
        startTime: "09:00",
        endTime: null,
        category: "FREE",
        title: { zh: "乔治市悠闲早晨", en: "Slow morning in George Town", ja: "ジョージタウンでのんびり午前" },
        locationName: { zh: "乔治市", en: "George Town", ja: "ジョージタウン" },
        note: {
          zh: "早上悠闲逛乔治市，约 11:00 退房。",
          en: "Slow morning in George Town. Check out around 11:00.",
          ja: "午前中はジョージタウンでゆっくり過ごし、午前11時ごろチェックアウト。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "11:00",
        endTime: null,
        category: "TRANSPORT",
        title: { zh: "渡轮＋ETS前往吉隆坡", en: "Ferry + ETS to KL Sentral", ja: "フェリー＋ETSでKLセントラルへ" },
        locationName: { zh: "北海 Butterworth", en: "Butterworth", ja: "バターワース" },
        note: {
          zh: "搭渡轮到北海，再乘下午 ETS 前往 KL Sentral。",
          en: "Ferry to Butterworth and take an afternoon ETS to KL Sentral.",
          ja: "フェリーでバターワースへ行き、午後のETSでKLセントラルへ移動します。",
        },
        cost: 78,
        url: null,
      },
      {
        startTime: null,
        endTime: null,
        category: "LODGING",
        title: { zh: "入住吉隆坡公寓（住4晚）", en: "Check in Kuala Lumpur apartment (4 nights)", ja: "クアラルンプールのアパートにチェックイン（4泊）" },
        locationName: { zh: "武吉免登", en: "Bukit Bintang", ja: "ブキッ・ビンタン" },
        note: {
          zh: "在吉隆坡同一间公寓住四晚，首选武吉免登附近。",
          en: "Check into one Kuala Lumpur apartment for four nights, preferably around Bukit Bintang.",
          ja: "クアラルンプールでは同じアパートに4泊。ブキッ・ビンタン周辺を第一候補にします。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "19:00",
        endTime: null,
        category: "SHOPPING",
        title: { zh: "柏威年・武吉免登・阿罗街", en: "Pavilion, Bukit Bintang & Jalan Alor", ja: "パビリオン・ブキッ・ビンタン・アロー通り" },
        locationName: { zh: "武吉免登", en: "Bukit Bintang", ja: "ブキッ・ビンタン" },
        note: {
          zh: "晚上逛柏威年、武吉免登和阿罗街。",
          en: "Evening at Pavilion, Bukit Bintang and Jalan Alor.",
          ja: "夜はパビリオン、ブキッ・ビンタン、アロー通りへ。",
        },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-10-29",
    title: { zh: "黑风洞 + 吉隆坡市中心 + 加影沙爹", en: "Batu Caves + central KL + Kajang satay", ja: "バトゥ洞窟 + KL中心部 + カジャンのサテー" },
    items: [
      {
        startTime: "07:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "黑风洞", en: "Batu Caves", ja: "バトゥ洞窟" },
        locationName: { zh: "黑风洞", en: "Batu Caves", ja: "バトゥ洞窟" },
        note: { zh: "约 07:00 前往黑风洞。", en: "Go to Batu Caves around 07:00.", ja: "午前7時ごろにバトゥ洞窟へ。" },
        cost: null,
        url: null,
      },
      {
        startTime: "10:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "茨厂街・独立广场・生命之河", en: "Chinatown, Merdeka Square & River of Life", ja: "チャイナタウン・ムルデカ広場・リバー・オブ・ライフ" },
        locationName: { zh: "吉隆坡市中心", en: "Central Kuala Lumpur", ja: "KL中心部" },
        note: {
          zh: "之后参观茨厂街、中央艺术坊、独立广场、苏丹阿都沙末大厦和生命之河。",
          en: "Continue to Chinatown, Petaling Street, Central Market, Merdeka Square, Sultan Abdul Samad Building and River of Life.",
          ja: "その後、チャイナタウン、プタリン通り、セントラルマーケット、ムルデカ広場、スルタン・アブドゥル・サマド・ビル、リバー・オブ・ライフを観光します。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "13:30",
        endTime: null,
        category: "FREE",
        title: { zh: "下午回公寓休息", en: "Afternoon rest", ja: "午後は休憩" },
        locationName: null,
        note: { zh: "下午回公寓休息。", en: "Rest in the afternoon.", ja: "午後は休憩します。" },
        cost: null,
        url: null,
      },
      {
        startTime: "16:30",
        endTime: null,
        category: "FOOD",
        title: { zh: "加影沙爹", en: "Kajang satay", ja: "カジャンのサテー" },
        locationName: { zh: "Stadium Kajang", en: "Stadium Kajang", ja: "Stadium Kajang駅" },
        note: {
          zh: "约 16:30–17:00 搭 MRT 加影线前往 Stadium Kajang，吃加影沙爹后搭 MRT 返回。",
          en: "Around 16:30–17:00, take the MRT Kajang Line to Stadium Kajang and have Kajang satay before returning by MRT.",
          ja: "午後4時30分〜5時ごろ、MRTカジャン線でStadium Kajang駅へ。サテーを食べてMRTで戻ります。",
        },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-10-30",
    title: { zh: "双威水上乐园", en: "Sunway Lagoon", ja: "サンウェイ・ラグーン" },
    items: [
      {
        startTime: "08:30",
        endTime: null,
        category: "TRANSPORT",
        title: { zh: "搭Grab前往双威水上乐园", en: "Grab to Sunway Lagoon", ja: "Grabでサンウェイ・ラグーンへ" },
        locationName: { zh: "双威", en: "Sunway", ja: "サンウェイ" },
        note: {
          zh: "约 08:30–09:00 出发。三人一起搭 Grab 最方便；公共交通可作为省钱方案。",
          en: "Leave around 08:30–09:00. Shared Grab is easiest for three people; public transport is the cheaper backup.",
          ja: "午前8時30分〜9時ごろに出発。3人ならGrabが便利で、公共交通は節約案です。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "09:30",
        endTime: null,
        category: "SIGHT",
        title: { zh: "双威水上乐园全天", en: "Sunway Lagoon full day", ja: "サンウェイ・ラグーン終日" },
        locationName: { zh: "双威水上乐园", en: "Sunway Lagoon", ja: "サンウェイ・ラグーン" },
        note: {
          zh: "全天游玩双威水上乐园。携带泳衣、凉鞋、防晒霜、防水手机袋和替换衣服。",
          en: "Full day at Sunway Lagoon. Bring swimwear, sandals, sunscreen, waterproof phone pouch and dry clothes.",
          ja: "サンウェイ・ラグーンを一日楽しみます。水着、サンダル、日焼け止め、防水スマホケース、着替えを持参します。",
        },
        cost: 245,
        url: "https://sunwaylagoon.com/pricing/",
      },
      {
        startTime: "19:00",
        endTime: null,
        category: "FOOD",
        title: { zh: "双威金字塔晚餐", en: "Dinner at Sunway Pyramid", ja: "サンウェイ・ピラミッドで夕食" },
        locationName: { zh: "双威金字塔", en: "Sunway Pyramid", ja: "サンウェイ・ピラミッド" },
        note: {
          zh: "结束后在双威金字塔吃晚餐，当晚不要再安排大型景点。",
          en: "Dinner at Sunway Pyramid. Do not schedule another major attraction that night.",
          ja: "終了後はサンウェイ・ピラミッドで夕食。この日はほかの大きな予定を入れません。",
        },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-10-31",
    title: { zh: "巴生肉骨茶 + KLCC", en: "Klang bak kut teh + KLCC", ja: "クランのバクテー + KLCC" },
    items: [
      {
        startTime: "07:30",
        endTime: null,
        category: "FOOD",
        title: { zh: "巴生肉骨茶早餐", en: "Klang bak kut teh breakfast", ja: "クランでバクテーの朝食" },
        locationName: { zh: "巴生", en: "Klang", ja: "クラン" },
        note: {
          zh: "早上较早前往巴生吃肉骨茶。三人一起搭 Grab 最方便。",
          en: "Leave early for Klang and have bak kut teh for breakfast. Shared Grab is easiest for three people.",
          ja: "朝早くクランへ行き、バクテーを朝食にします。3人ならGrabが簡単です。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "09:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "巴生老城区・小印度", en: "Historic Klang & Little India", ja: "クラン旧市街・リトル・インディア" },
        locationName: { zh: "巴生", en: "Klang", ja: "クラン" },
        note: {
          zh: "简单逛巴生老城区或小印度，中午前后返回吉隆坡休息。",
          en: "Walk briefly around historic Klang or Little India, then return to KL around lunchtime and rest.",
          ja: "クラン旧市街やリトル・インディアを短く歩き、昼ごろKLへ戻って休憩。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "12:30",
        endTime: null,
        category: "FREE",
        title: { zh: "返回吉隆坡休息", en: "Return to KL & rest", ja: "KLへ戻って休憩" },
        locationName: null,
        note: null,
        cost: null,
        url: null,
      },
      {
        startTime: "18:00",
        endTime: null,
        category: "SIGHT",
        title: { zh: "KLCC公园・双子塔・莎罗马天桥", en: "KLCC Park, Twin Towers & Saloma Link", ja: "KLCC公園・ツインタワー・サロマ・リンク" },
        locationName: { zh: "KLCC", en: "KLCC", ja: "KLCC" },
        note: {
          zh: "傍晚参观 KLCC 公园、国油双子塔、阳光广场和莎罗马行人天桥。登塔为可选项目。",
          en: "Evening at KLCC Park, PETRONAS Twin Towers, Suria KLCC and Saloma Link. Twin Towers admission is optional.",
          ja: "夕方はKLCC公園、ペトロナス・ツインタワー、スリアKLCC、サロマ・リンクへ。展望台は任意です。",
        },
        cost: null,
        url: null,
      },
    ],
  },
  {
    date: "2026-11-01",
    title: { zh: "吉隆坡最后一天 + 回程", en: "Final KL day + flight", ja: "KL最終日 + 帰国便" },
    items: [
      {
        startTime: "08:00",
        endTime: null,
        category: "FOOD",
        title: { zh: "公寓附近或KL Sentral早餐", en: "Breakfast near apartment / KL Sentral", ja: "アパート付近/KLセントラルで朝食" },
        locationName: { zh: "KL Sentral", en: "KL Sentral", ja: "KLセントラル" },
        note: {
          zh: "出发前可以在公寓附近或 KL Sentral 吃早餐。",
          en: "Have breakfast near the apartment or KL Sentral before leaving.",
          ja: "朝食はアパート周辺またはKLセントラルで済ませます。",
        },
        cost: null,
        url: null,
      },
      {
        startTime: "09:30",
        endTime: null,
        category: "TRANSPORT",
        title: { zh: "退房・KLIA Ekspres前往机场", en: "Check out & KLIA Ekspres to airport", ja: "チェックアウト・KLIAエクスプレスで空港へ" },
        locationName: { zh: "KL Sentral", en: "KL Sentral", ja: "KLセントラル" },
        note: {
          zh: "回程航班是 14:00，建议约 08:30–09:00 退房，前往 KL Sentral，并在 09:30–10:00 左右搭 KLIA Ekspres，目标在起飞前约三小时抵达 KLIA。",
          en: "With the return flight at 14:00, check out around 08:30–09:00, travel to KL Sentral, and take KLIA Ekspres around 09:30–10:00 to reach KLIA roughly three hours before departure.",
          ja: "帰国便は14:00なので、午前8時30分〜9時ごろにチェックアウトしてKLセントラルへ移動し、午前9時30分〜10時ごろのKLIAエクスプレスを目安にします。出発の約3時間前にKLIAへ到着できるようにします。",
        },
        cost: 48,
        url: "https://www.kliaekspres.com/products-fares/klia-ekspres/",
      },
      {
        startTime: "14:00",
        endTime: null,
        category: "TRANSPORT",
        title: { zh: "回程航班", en: "Return flight", ja: "帰国便" },
        locationName: { zh: "KLIA", en: "KLIA", ja: "KLIA" },
        note: {
          zh: "航班是 14:00，所以最后一天不要安排观光。",
          en: "Return flight at 14:00 — do not plan sightseeing on the final day.",
          ja: "帰国便は14:00なので、最終日は観光を入れません。",
        },
        cost: null,
        url: null,
      },
    ],
  },
];
